# Generated by Django 2.2.4 on 2019-08-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190813_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discord',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faceit',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
