# Generated by Django 2.2.4 on 2019-08-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='verified_student',
        ),
    ]
