# Generated by Django 2.2.4 on 2019-08-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190813_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
