# Generated by Django 2.2.4 on 2019-08-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190820_0039'),
        ('users', '0011_auto_20190819_0414'),
    ]

    operations = [
    ]
