# Generated by Django 2.2.4 on 2019-08-26 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduateformmodel',
            options={'verbose_name': 'Graduated Student Application', 'verbose_name_plural': 'Graduated Student Applications'},
        ),
        migrations.AlterModelOptions(
            name='highschoolformmodel',
            options={'verbose_name': 'High School Student Application', 'verbose_name_plural': 'High School Student Applications'},
        ),
        migrations.AddField(
            model_name='graduateformmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highschoolformmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
